version: "3.8"

services:
  backend:
    build:
      context: ./wanderquest-backend
    container_name: nestjs-backend
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build:
      context: ./wanderquest-frontend
    container_name: nextjs-frontend
    env_file:
      - .env
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
